### ISSUE TITLE
Loss function

### ISSUE THREAD

**Issue by Auth0rM0rgan** [Tandon-A/CycleGAN_ssim#2]

**Comment by Tandon-A** [comment]
For the loss functions, I have referred the paper, [Loss Functions for Image Restoration with Neural
Networks](https://ieeexplore.ieee.org/document/7797130). The researchers in this paper have used MS-SSIM with L1 and L2 have set the alpha parameter as 0.84. 

For the other combination of SSIM and L2, the 0.00005 is the weight for the L2 regularisation term. I referred this [paper](http://cs231n.stanford.edu/reports/2017/pdfs/305.pdf) for this combination. 

In this project, I am trying to use these different loss functions for the cyclic loss of the cycleGAN model and compare the generated images.
